
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: styleswap
    ports:
      - "3306:3306"
    platform: linux/amd64
    networks:
      - app-network

  app:
    container_name: app
    build:
      context: .
    ports:
      - "80:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/styleswap
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app-network
    platform: linux/amd64


networks:
  app-network:
