
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: styleswap
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
